import json
import os

BACKUP_PATH = 'supabase/backups/backup_2026_09_20_210002/users.json'
OUTPUT_SQL = 'supabase/fix_dobby_attack_and_database_lockdown.sql'

with open(BACKUP_PATH, 'r', encoding='utf-8') as f:
    backup_users = json.load(f)

print(f"Loaded {len(backup_users)} backup users.")

sql_lines = []
sql_lines.append("-- ==============================================================================")
sql_lines.append("-- POLYGON GAMING: COMPREHENSIVE INCIDENT REMEDIATION & DATABASE LOCKDOWN")
sql_lines.append("-- Target Incident: Malicious bulk fake user injection & referral hijacking")
sql_lines.append("-- Attacker Account: Dobby TheDEV (0xpgt003e7625 / 0x602BEc371e2A99f679C73A5930a590CeBf8e7696)")
sql_lines.append("-- ==============================================================================")
sql_lines.append("")
sql_lines.append("BEGIN;")
sql_lines.append("")
sql_lines.append("-- ------------------------------------------------------------------------------")
sql_lines.append("-- STEP 1: Purge all 6,051 unauthenticated fake bot injection rows created today")
sql_lines.append("-- ------------------------------------------------------------------------------")
sql_lines.append("DELETE FROM public.users")
sql_lines.append("WHERE created_at >= '2026-09-21T00:00:00Z'")
sql_lines.append("  AND user_id IS NULL;")
sql_lines.append("")
sql_lines.append("-- ------------------------------------------------------------------------------")
sql_lines.append("-- STEP 2: Restore all 242 legitimate users' original referral uplines (from backup)")
sql_lines.append("-- ------------------------------------------------------------------------------")
sql_lines.append("CREATE TEMP TABLE backup_user_referrers (")
sql_lines.append("    player_id TEXT PRIMARY KEY,")
sql_lines.append("    original_l1 TEXT")
sql_lines.append(");")
sql_lines.append("")
sql_lines.append("INSERT INTO backup_user_referrers (player_id, original_l1) VALUES")

val_rows = []
for u in backup_users:
    pid = u['player_id']
    l1 = u.get('referred_by_l1')
    if l1 is None:
        val_rows.append(f"('{pid}', NULL)")
    else:
        escaped_l1 = l1.replace("'", "''")
        val_rows.append(f"('{pid}', '{escaped_l1}')")

sql_lines.append(",\n".join(val_rows) + ";")
sql_lines.append("")
sql_lines.append("UPDATE public.users u")
sql_lines.append("SET referred_by_l1 = b.original_l1")
sql_lines.append("FROM backup_user_referrers b")
sql_lines.append("WHERE u.player_id = b.player_id;")
sql_lines.append("")
sql_lines.append("DROP TABLE backup_user_referrers;")
sql_lines.append("")
sql_lines.append("-- ------------------------------------------------------------------------------")
sql_lines.append("-- STEP 3: Reassign hijacked referral commissions to their authentic uplines")
sql_lines.append("-- ------------------------------------------------------------------------------")
sql_lines.append("-- Poss (0xpgt8312e02d37185b5983e6922d1dae1cce) is the true upline for Vezuvius King, CRiMiNeL, and Paul V:")
sql_lines.append("UPDATE public.referral_commissions")
sql_lines.append("SET upline_player_id = '0xpgt8312e02d37185b5983e6922d1dae1cce'")
sql_lines.append("WHERE upline_player_id = '0xpgt003e7625'")
sql_lines.append("  AND downline_player_id IN ('0xpgt1340d9e6', '0xpgt25c12fd2', '0xpgt3a44cee7');")
sql_lines.append("")
sql_lines.append("-- Paul V (0xpgt3a44cee7) is the true upline for Cybermix and TopTop:")
sql_lines.append("UPDATE public.referral_commissions")
sql_lines.append("SET upline_player_id = '0xpgt3a44cee7'")
sql_lines.append("WHERE upline_player_id = '0xpgt003e7625'")
sql_lines.append("  AND downline_player_id IN ('0xpgt58f5eb8c', '0xpgt9ddc0ca3');")
sql_lines.append("")
sql_lines.append("-- ------------------------------------------------------------------------------")
sql_lines.append("-- STEP 4: Credit stolen commissions to legitimate uplines & strip gains from Dobby")
sql_lines.append("-- ------------------------------------------------------------------------------")
sql_lines.append("-- Re-credit Poss (+314.916 PGT):")
sql_lines.append("UPDATE public.users")
sql_lines.append("SET unclaimed_referral_pgt = COALESCE(unclaimed_referral_pgt, 0) + 314.916,")
sql_lines.append("    total_referral_commission = COALESCE(total_referral_commission, 0) + 314.916")
sql_lines.append("WHERE player_id = '0xpgt8312e02d37185b5983e6922d1dae1cce';")
sql_lines.append("")
sql_lines.append("-- Re-credit Paul V (+18.35 PGT):")
sql_lines.append("UPDATE public.users")
sql_lines.append("SET unclaimed_referral_pgt = COALESCE(unclaimed_referral_pgt, 0) + 18.35,")
sql_lines.append("    total_referral_commission = COALESCE(total_referral_commission, 0) + 18.35")
sql_lines.append("WHERE player_id = '0xpgt3a44cee7';")
sql_lines.append("")
sql_lines.append("-- Strip Dobby's illicit gains and ban the account:")
sql_lines.append("UPDATE public.users")
sql_lines.append("SET unclaimed_referral_pgt = 0.0,")
sql_lines.append("    total_referral_commission = 0.0,")
sql_lines.append("    referrals_count = 0,")
sql_lines.append("    referrals_l1 = 0,")
sql_lines.append("    referrals_list = '[]'::jsonb,")
sql_lines.append("    is_banned = true,")
sql_lines.append("    bot_warning = 99")
sql_lines.append("WHERE player_id = '0xpgt003e7625' OR linked_wallet_address ILIKE '0x602BEc371e2A99f679C73A5930a590CeBf8e7696';")
sql_lines.append("")
sql_lines.append("-- ------------------------------------------------------------------------------")
sql_lines.append("-- STEP 5: Dynamic RLS Policy Purge & Table-Level Privilege Lockdown on public.users")
sql_lines.append("-- ------------------------------------------------------------------------------")
sql_lines.append("DO $$")
sql_lines.append("DECLARE")
sql_lines.append("    r RECORD;")
sql_lines.append("BEGIN")
sql_lines.append("    FOR r IN (SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'users') LOOP")
sql_lines.append("        EXECUTE 'DROP POLICY IF EXISTS ' || quote_ident(r.policyname) || ' ON public.users';")
sql_lines.append("    END LOOP;")
sql_lines.append("END $$;")
sql_lines.append("")
sql_lines.append("-- Table-level grants: revoke all write permissions from anon/public")
sql_lines.append("REVOKE ALL ON TABLE public.users FROM anon, public;")
sql_lines.append("GRANT SELECT ON TABLE public.users TO anon, authenticated, service_role;")
sql_lines.append("GRANT INSERT, UPDATE ON TABLE public.users TO authenticated;")
sql_lines.append("GRANT ALL ON TABLE public.users TO service_role, postgres;")
sql_lines.append("")
sql_lines.append("-- Strict RLS enforcement")
sql_lines.append("ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;")
sql_lines.append("ALTER TABLE public.users FORCE ROW LEVEL SECURITY;")
sql_lines.append("")
sql_lines.append("CREATE POLICY \"Allow public read users\" ON public.users")
sql_lines.append("    FOR SELECT TO anon, authenticated, service_role")
sql_lines.append("    USING (true);")
sql_lines.append("")
sql_lines.append("CREATE POLICY \"Allow authenticated insert users\" ON public.users")
sql_lines.append("    FOR INSERT TO authenticated")
sql_lines.append("    WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid());")
sql_lines.append("")
sql_lines.append("CREATE POLICY \"Allow authenticated update users\" ON public.users")
sql_lines.append("    FOR UPDATE TO authenticated")
sql_lines.append("    USING (auth.uid() IS NOT NULL AND user_id = auth.uid())")
sql_lines.append("    WITH CHECK (auth.uid() IS NOT NULL AND user_id = auth.uid());")
sql_lines.append("")
sql_lines.append("-- Schema-wide protection: revoke write permissions from anon/public on ALL public tables")
sql_lines.append("REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public FROM anon, public;")
sql_lines.append("")
sql_lines.append("-- ------------------------------------------------------------------------------")
sql_lines.append("-- STEP 6: Deploy Patched assert_caller_player_id (Rejects anon & SECURITY DEFINER bypass)")
sql_lines.append("-- ------------------------------------------------------------------------------")
sql_lines.append("CREATE OR REPLACE FUNCTION public.assert_caller_player_id(")
sql_lines.append("  p_target_id TEXT,")
sql_lines.append("  OUT p_status TEXT,")
sql_lines.append("  OUT p_player_id TEXT,")
sql_lines.append("  OUT p_error_msg TEXT")
sql_lines.append(")")
sql_lines.append("RETURNS RECORD")
sql_lines.append("LANGUAGE plpgsql")
sql_lines.append("SECURITY DEFINER")
sql_lines.append("SET search_path = public, extensions")
sql_lines.append("AS $$")
sql_lines.append("DECLARE")
sql_lines.append("  v_role TEXT := auth.role();")
sql_lines.append("  v_auth_uid UUID := auth.uid();")
sql_lines.append("  v_caller_pid TEXT;")
sql_lines.append("  v_resolved_target TEXT;")
sql_lines.append("BEGIN")
sql_lines.append("  -- 1. Explicitly reject unauthenticated web/REST clients (anon role or missing uid on web):")
sql_lines.append("  IF v_role = 'anon' OR (v_role = 'authenticated' AND v_auth_uid IS NULL) THEN")
sql_lines.append("    p_status := 'UNAUTHENTICATED';")
sql_lines.append("    p_player_id := NULL;")
sql_lines.append("    p_error_msg := 'AUTHENTICATION_REQUIRED: Please sign in with Google or connect your wallet.';")
sql_lines.append("    RETURN;")
sql_lines.append("  END IF;")
sql_lines.append("")
sql_lines.append("  -- 2. Allow internal server execution:")
sql_lines.append("  -- Allowed only for service_role or direct background DB triggers/jobs without JWT context")
sql_lines.append("  IF v_role = 'service_role' OR (v_role IS NULL AND v_auth_uid IS NULL) THEN")
sql_lines.append("    p_status := 'OK';")
sql_lines.append("    p_player_id := public.resolve_player_id(p_target_id);")
sql_lines.append("    p_error_msg := NULL;")
sql_lines.append("    RETURN;")
sql_lines.append("  END IF;")
sql_lines.append("")
sql_lines.append("  -- 3. Caller MUST have an authentic Supabase Auth session")
sql_lines.append("  IF v_auth_uid IS NULL THEN")
sql_lines.append("    p_status := 'UNAUTHENTICATED';")
sql_lines.append("    p_player_id := NULL;")
sql_lines.append("    p_error_msg := 'AUTHENTICATION_REQUIRED: Please sign in with Google or connect your wallet.';")
sql_lines.append("    RETURN;")
sql_lines.append("  END IF;")
sql_lines.append("")
sql_lines.append("  -- 4. Lookup caller's player_id in public.users")
sql_lines.append("  SELECT player_id INTO v_caller_pid")
sql_lines.append("  FROM public.users")
sql_lines.append("  WHERE user_id = v_auth_uid")
sql_lines.append("  LIMIT 1;")
sql_lines.append("")
sql_lines.append("  IF v_caller_pid IS NULL THEN")
sql_lines.append("    p_status := 'PROFILE_NOT_FOUND';")
sql_lines.append("    p_player_id := NULL;")
sql_lines.append("    p_error_msg := 'PROFILE_NOT_FOUND: User profile does not exist for this session.';")
sql_lines.append("    RETURN;")
sql_lines.append("  END IF;")
sql_lines.append("")
sql_lines.append("  -- 5. Anti-Framing Assertion:")
sql_lines.append("  -- If target ID was passed by client, it MUST resolve to the caller's own player_id.")
sql_lines.append("  IF p_target_id IS NOT NULL AND TRIM(p_target_id) <> '' THEN")
sql_lines.append("    v_resolved_target := public.resolve_player_id(p_target_id);")
sql_lines.append("    IF v_resolved_target IS NOT NULL AND LOWER(v_resolved_target) <> LOWER(v_caller_pid) THEN")
sql_lines.append("      PERFORM public.record_bot_warning(")
sql_lines.append("        v_caller_pid,")
sql_lines.append("        'identity_impersonation_attempt',")
sql_lines.append("        'Security Sentinel',")
sql_lines.append("        jsonb_build_object('attempted_target', p_target_id, 'resolved_target', v_resolved_target)")
sql_lines.append("      );")
sql_lines.append("      p_status := 'MISMATCH';")
sql_lines.append("      p_player_id := v_caller_pid;")
sql_lines.append("      p_error_msg := 'SECURITY_VIOLATION: You cannot perform actions on behalf of another player.';")
sql_lines.append("      RETURN;")
sql_lines.append("    END IF;")
sql_lines.append("  END IF;")
sql_lines.append("")
sql_lines.append("  p_status := 'OK';")
sql_lines.append("  p_player_id := v_caller_pid;")
sql_lines.append("  p_error_msg := NULL;")
sql_lines.append("  RETURN;")
sql_lines.append("END;")
sql_lines.append("$$;")
sql_lines.append("")
sql_lines.append("GRANT EXECUTE ON FUNCTION public.assert_caller_player_id(TEXT) TO authenticated, service_role;")
sql_lines.append("REVOKE EXECUTE ON FUNCTION public.assert_caller_player_id(TEXT) FROM anon, public;")
sql_lines.append("")
sql_lines.append("-- ------------------------------------------------------------------------------")
sql_lines.append("-- STEP 7: Permanent Schema Invariants (No wallet_address)")
sql_lines.append("-- ------------------------------------------------------------------------------")
sql_lines.append("ALTER TABLE public.users DROP COLUMN IF EXISTS wallet_address;")
sql_lines.append("DROP INDEX IF EXISTS public.idx_users_wallet_address;")
sql_lines.append("")
sql_lines.append("COMMIT;")
sql_lines.append("")

with open(OUTPUT_SQL, 'w', encoding='utf-8') as f:
    f.write("\n".join(sql_lines))

print(f"Generated {OUTPUT_SQL} with {len(sql_lines)} lines.")
